# Generated by Django 5.0.7 on 2024-08-07 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_department_employeedetails_delete_workproject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('training_provider', models.CharField(max_length=200)),
                ('training_location', models.CharField(choices=[('PREMISE', 'Premise'), ('REMOTE', 'Remote'), ('HYBRID', 'Hybrid')], max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.DurationField()),
                ('start_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='JobRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('required_level', models.CharField(choices=[('BEGINER', 'Beginer'), ('INTERMEDIATE', 'Female'), ('ADVANCED', 'Advanced')], max_length=100)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.skill')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('expected_completion_date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.employeedetails')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.training')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_level', models.CharField(choices=[('BEGINER', 'Beginer'), ('INTERMEDIATE', 'Female'), ('ADVANCED', 'Advanced')], max_length=100)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.employeedetails')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.skill')),
            ],
            options={
                'unique_together': {('employee', 'skill')},
            },
        ),
    ]
