# Generated by Django 5.0.7 on 2024-08-07 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_skill_training_jobrequirement_trainingneed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeedetails',
            options={'verbose_name': 'Employee Detail', 'verbose_name_plural': 'Employee Detail'},
        ),
    ]
